### ISSUE TITLE
segment fault in poisson_surface_reconstruction_delaunay

### ISSUE THREAD

**Issue by Ashitaka98** [CGAL/cgal#4794]
## Issue Details

segfault occurred repeatedly in CGAL::poisson_surface_reconstruction_delaunay
I'm suspecting the error is for mutable std::vector<Triplet> m_triplets of
struct Eigen_sparse_matrix in Eigen_matrix.h is not aligned
here is the backtrace status when error occurred:

```
#0  0x00005655555b788c in Eigen::internal::scalar_sum_op<double>::operator() (
    this=<optimized out>, a=<error reading variable>, b=<optimized out>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/Functors.h:509
509	  EIGEN_STRONG_INLINE Scalar operator() (const Scalar& a) const { return a * m_other; }
---Type <return> to continue, or q <return> to quit---bt
[Current thread is 1 (Thread 0x7efbff6d2b40 (LWP 7266))]
(gdb) bt
#0  0x00005655555b788c in Eigen::internal::scalar_sum_op<double>::operator() (
    this=<optimized out>, a=<error reading variable>, b=<optimized out>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/Functors.h:509
#1  Eigen::SelfCwiseBinaryOp<Eigen::internal::scalar_sum_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1, 1, false>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> >::copyCoeff<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> > (this=<synthetic pointer>, 
    other=<synthetic pointer>..., index=0)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/SelfCwiseBinaryOp.h:103
#2  Eigen::internal::assign_LinearTraversal_CompleteUnrolling<Eigen::SelfCwiseBinaryOp<Eigen::internal::scalar_sum_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1, 1, false>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> >, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const>, 0, 1>::run (src=<synthetic pointer>..., dst=<synthetic pointer>...)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/Assign.h:180
#3  Eigen::internal::assign_impl<Eigen::SelfCwiseBinaryOp<Eigen::internal::scala---Type <return> to continue, or q <return> to quit---return
r_sum_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1, 1, false>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> >, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const>, 1, 2, 0>::run (
    src=<synthetic pointer>..., dst=<synthetic pointer>...)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/Assign.h:314
#4  Eigen::SelfCwiseBinaryOp<Eigen::internal::scalar_sum_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1, 1, false>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> >::lazyAssign<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> > (rhs=<synthetic pointer>..., 
    this=<synthetic pointer>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/SelfCwiseBinaryOp.h:137
#5  Eigen::internal::assign_selector<Eigen::SelfCwiseBinaryOp<Eigen::internal::scalar_sum_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1, 1, false>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> >, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const>, false, false>::run
---Type <return> to continue, or q <return> to quit---
    (other=<synthetic pointer>..., dst=<synthetic pointer>...)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/Assign.h:527
#6  Eigen::MatrixBase<Eigen::SelfCwiseBinaryOp<Eigen::internal::scalar_sum_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1, 1, false>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> > >::operator=<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> > (
    other=<synthetic pointer>..., this=<synthetic pointer>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/Assign.h:571
#7  Eigen::SelfCwiseBinaryOp<Eigen::internal::scalar_sum_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1, 1, false>, Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> >::operator= (_rhs=..., 
    this=<synthetic pointer>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/SelfCwiseBinaryOp.h:150
#8  Eigen::MatrixBase<Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1, 1, false> >::operator+=<Eigen::CwiseUnaryOp<Eigen::internal::scalar_multiple_op<double>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, 1, 1, false> const> > (other=..., this=<optimized out>)
---Type <return> to continue, or q <return> to quit---
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/CwiseBinaryOp.h:224
#9  Eigen::SparseSelfAdjointTimeDenseProduct<Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1>::scaleAndAddTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (alpha=<optimized out>, dest=..., 
    this=<optimized out>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/SparseCore/SparseSelfAdjointView.h:266
#10 Eigen::ProductBase<Eigen::SparseSelfAdjointTimeDenseProduct<Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1>, Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1> >::scaleAndAddTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (alpha=<optimized out>, 
    dst=..., this=<optimized out>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/ProductBase.h:118
#11 Eigen::ProductBase<Eigen::SparseSelfAdjointTimeDenseProduct<Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1>, Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1> >::evalTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (dst=..., this=<optimized out>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/ProductBase.h:109
#12 Eigen::MatrixBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> >::lazyAssign<Eigen---Type <return> to continue, or q <return> to quit---
::SparseSelfAdjointTimeDenseProduct<Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1>, Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1> > (other=..., this=0x7ffbffff99b0)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/ProductBase.h:284
#13 Eigen::PlainObjectBase<Eigen::Matrix<double, -1, 1, 0, -1, 1> >::lazyAssign<Eigen::SparseSelfAdjointTimeDenseProduct<Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1> > (other=..., 
    this=0x7ffbffff99b0)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/PlainObjectBase.h:414
#14 Eigen::internal::assign_selector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::SparseSelfAdjointTimeDenseProduct<Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1>, false, false>::run (other=..., 
    dst=...)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/Assign.h:527
#15 Eigen::NoAlias<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::MatrixBase>::operator=<Eigen::SparseSelfAdjointTimeDenseProduct<Eigen::SparseMatrix<double, 0, int> const, Eigen::Matrix<double, -1, 1, 0, -1, 1>, 1> > (
    this=<optimized out>, other=...)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/NoAlias.h:41
---Type <return> to continue, or q <return> to quit---
#16 Eigen::internal::conjugate_gradient<Eigen::SparseSelfAdjointView<Eigen::SparseMatrix<double, 0, int> const, 1u>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1> const, -1, 1, true>, Eigen::Block<Eigen::Matrix<double, -1, 1, 0, -1, 1>, -1, 1, true>, Eigen::DiagonalPreconditioner<double> > (mat=..., rhs=..., 
    x=..., precond=..., iters=@0x565559a59c28: 6160665, 
    tol_error=@0x565559a59c20: 2.2204460492503131e-16)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h:70
#17 0x00005655555e9754 in Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> >::_solveWithGuess<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> > (x=..., 
    b=..., this=0x565559a59bb0)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/PlainObjectBase.h:687
#18 Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> >::_solve<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1> > (x=..., b=..., this=0x565559a59bb0)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h:231
#19 Eigen::internal::solve_retval<Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> >, Eigen::Matrix<double---Type <return> to continue, or q <return> to quit---
, -1, 1, 0, -1, 1> >::evalTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (
    dst=..., this=<optimized out>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h:250
#20 Eigen::internal::solve_retval_base<Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> >, Eigen::Matrix<double, -1, 1, 0, -1, 1> >::evalTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (
    dst=..., this=<optimized out>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/misc/Solve.h:51
#21 Eigen::ReturnByValue<Eigen::internal::solve_retval_base<Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> >, Eigen::Matrix<double, -1, 1, 0, -1, 1> > >::evalTo<Eigen::Matrix<double, -1, 1, 0, -1, 1> > (dst=..., this=<optimized out>)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/ReturnByValue.h:61
#22 Eigen::Matrix<double, -1, 1, 0, -1, 1>::Matrix<Eigen::internal::solve_retval_base<Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> >, Eigen::Matrix<double, -1, 1, 0, -1, 1> > > (
    other=..., this=0x7ffbffff9b10)
    at /home/zeru/.conan/data/eigen/3.2.10/oppen/testing/package/20255e92456915b15afbdb13e39c17e00e395a72/include/eigen3/Eigen/src/Core/Matrix.h:311
---Type <return> to continue, or q <return> to quit---
#23 CGAL::Eigen_solver_traits<Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> > >::linear_solver (
    D=<synthetic pointer>: <optimized out>, X=..., B=..., A=..., 
    this=0x7ffbffff9ea0) at /usr/local/include/CGAL/Eigen_solver_traits.h:154
#24 CGAL::Poisson_reconstruction_function<CGAL::Epick>::solve_poisson<CGAL::Eigen_solver_traits<Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> > > > (this=this@entry=0x7ffbffffa370, 
    solver=..., lambda=lambda@entry=0.10000000000000001)
    at /usr/local/include/CGAL/Poisson_reconstruction_function.h:765
#25 0x00005655555f52e4 in CGAL::Poisson_reconstruction_function<CGAL::Epick>::compute_implicit_function<CGAL::Eigen_solver_traits<Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> > >, CGAL::Poisson_visitor> (this=this@entry=0x7ffbffffa370, solver=..., visitor=..., 
    approximation_ratio=approximation_ratio@entry=0, 
    average_spacing_ratio=average_spacing_ratio@entry=5)
    at /usr/include/c++/8/bits/atomic_base.h:512
#26 0x00005655555fa786 in CGAL::Poisson_reconstruction_function<CGAL::Epick>::compute_implicit_function<CGAL::Eigen_solver_traits<Eigen::ConjugateGradient<Eigen::SparseMatrix<double, 0, int>, 1, Eigen::DiagonalPreconditioner<double> > > >
    (smoother_hole_filling=false, solver=..., this=0x7ffbffffa370)
    at /usr/include/c++/8/bits/atomic_base.h:512
#27 CGAL::Poisson_reconstruction_function<CGAL::Epick>::compute_implicit_function (smoother_hole_filling=false, this=0x7ffbffffa370)
---Type <return> to continue, or q <return> to quit---
    at /usr/local/include/CGAL/Poisson_reconstruction_function.h:536
#28 CGAL::poisson_surface_reconstruction_delaunay<__gnu_cxx::__normal_iterator<std::tuple<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >*, std::vector<std::tuple<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> >, std::allocator<std::tuple<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> > > > >, CGAL::Nth_of_tuple_property_map<0, std::tuple<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> > >, CGAL::Nth_of_tuple_property_map<1, std::tuple<CGAL::Point_3<CGAL::Epick>, CGAL::Vector_3<CGAL::Epick> > >, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Simple_cartesian<float> > >, CGAL::Manifold_tag> (begin=..., 
    end=..., point_map=..., normal_map=..., output_mesh=..., 
    spacing=0.00022810482187196612, sm_angle=sm_angle@entry=20, 
    sm_radius=sm_radius@entry=100, sm_distance=sm_distance@entry=0.375, 
    tag=...) at /usr/local/include/CGAL/poisson_surface_reconstruction.h:107
```

## Source Code

```
CGAL::poisson_surface_reconstruction_delaunay
    (dpoints.begin(), dpoints.end(),
    dPoint_map(),
    dNormal_map(),
    output_mesh, spacing*average_spacing,
    20,100,0.375,CGAL::Manifold_tag()
    )
```

## Environment

* Operating system Ubuntu 18.04 :
* Compiler:g++ 8
* Release or debug mode: release
* Specific flags used (if any): 
* CGAL version:5.0.2
* Boost version:1.67
* Other libraries versions if used (Eigen, TBB, etc.):Eigen3.2.10 TBB/2020.1

**Comment by afabri** [comment]
Hello, can you please put a complete compilable source code on gist.github.com   together with a data set.

**Comment by MaelRL** [comment]
@Ashitaka98 bump

**Comment by MaelRL** [comment]
Feel free to re-open if you still encounter the issue (but please provide data).
