### ISSUE TITLE
CGAL::Surface_mesh_shortest_path traits dangling reference

### ISSUE THREAD

**Issue by seb-tourneux** [CGAL/cgal#6333]
Hello,
I am regularly checking my code with clang's AddressSanitizer (ASAN), and it found an error inside CGAL's Surface_mesh_shortest_path.

This code produces a dangling reference, when using the default argument for `traits`, as member `m_traits` is a reference, thus in this case, a reference to a temporary object :

https://github.com/CGAL/cgal/blob/adb3e7a3e7ec445e0fbeadc97af1cfdaf30abbe8/Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h#L2202-L2204

https://github.com/CGAL/cgal/blob/adb3e7a3e7ec445e0fbeadc97af1cfdaf30abbe8/Surface_mesh_shortest_path/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h#L334

Here is an example :
```c++
Surface_mesh_shortest_path shortest_paths(surfaceMesh);
// ... use shortest_paths, but m_traits is a dangling reference


// Not using the default argument and manually creating the traits works, 
// as this m_traits lifetime is the same as shortest_paths
Surface_mesh_shortest_path_traits traits{};
Surface_mesh_shortest_path shortest_paths(surfaceMesh, traits);
// ... use shortest_paths, OK
```

ASAN error and backtrace :

```
==3110668==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7f498e1368e7 at pc 0x0000002d6b77 bp 0x7ffef721c010 sp 0x7ffef721b7d8
READ of size 39 at 0x7f498e1368e7 thread T0
    #0 0x2d6b76 in __asan_memcpy (path/to/bin+0x2d6b76)
    #1 0x7f49c5b90320 in CGAL::Surface_mesh_shortest_path_traits<CGAL::Epick, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >::is_saddle_vertex_object() const path/to/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path_traits.h:133:61
    #2 0x7f49c5b90320 in CGAL::Surface_mesh_shortest_path<CGAL::Surface_mesh_shortest_path_traits<CGAL::Epick, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::is_saddle_vertex(CGAL::SM_Vertex_index) const path/to/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h:1621:21
    #3 0x7f49c5b90320 in CGAL::Surface_mesh_shortest_path<CGAL::Surface_mesh_shortest_path_traits<CGAL::Epick, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::set_vertex_types() path/to/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h:1615:46
    #4 0x7f49c5b8a636 in CGAL::Surface_mesh_shortest_path<CGAL::Surface_mesh_shortest_path_traits<CGAL::Epick, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::construct_sequence_tree_internal() path/to/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h:1980:5
    #5 0x7f49c5b66e40 in CGAL::Surface_mesh_shortest_path<CGAL::Surface_mesh_shortest_path_traits<CGAL::Epick, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::build_sequence_tree() path/to/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h:2390:7
    #6 0x7f49c5b66e40 in std::pair<double, CGAL::Surface_mesh_shortest_path<CGAL::Surface_mesh_shortest_path_traits<CGAL::Epick, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::Source_point_iterator> CGAL::Surface_mesh_shortest_path<CGAL::Surface_mesh_shortest_path_traits<CGAL::Epick, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >, CGAL::Default, CGAL::Default, CGAL::Default, CGAL::Default>::shortest_path_points_to_source_points<std::back_insert_iterator<std::vector<CGAL::Point_3<CGAL::Epick>, std::allocator<CGAL::Point_3<CGAL::Epick> > > > >(CGAL::SM_Vertex_index, std::back_insert_iterator<std::vector<CGAL::Point_3<CGAL::Epick>, std::allocator<CGAL::Point_3<CGAL::Epick> > > >) path/to/include/CGAL/Surface_mesh_shortest_path/Surface_mesh_shortest_path.h:2622:5
```

**Comment by afabri** [comment]
I would say it should always be const value.
