### ISSUE TITLE
ARAP parameterization crashes the session

### ISSUE THREAD

**Issue by stla** [CGAL/cgal#7506]
Hello,

I tried the ARAP parameterization with multiple examples and it always crashed the session (segfault, memory not mapped). Now I've just tried with the mesh `head.off` as in [the example](https://doc.cgal.org/latest/Surface_mesh_parameterization/Surface_mesh_parameterization_2ARAP_parameterization_8cpp-example.html), and same result: crash.

## Environment

* Operating system: Linux Mint 20
* Compiler: gcc
* Release or debug mode: release
* Specific flags used (if any): ?
* CGAL version: 5.5.2
* Boost version: 1.81
* Other libraries versions if used (Eigen, TBB, etc.): Eigen 3.3.9

**Comment by afabri** [comment]
What about debug build and stacktrace?
Without that your issue is sad, but what do you expect from others.

**Comment by stla** [comment]
You believe I'm a C++ professional ? ^^ I don't know what is debug build and how to get a stacktrace. But I know a debug option, I will try it.

**Comment by stla** [comment]
Sorry, my debug option did nothing more. Could **gbd** be helpful?

**Comment by stla** [comment]
Here is what I get with **gdb**:

```
Thread 1 "R" received signal SIGSEGV, Segmentation fault.
0x00007fffc633e69d in CGAL::internal::chained_map<std::pair<int, int>, std::allocator<std::pair<int, int> > >::access (x=4636, this=0x7fffffff9e38)
    at /home/stla/R/x86_64-pc-linux-gnu-library/4.3/RcppCGAL/include/CGAL/Hash_map/internal/chained_map.h:64
64	   chained_map_elem<T>*  HASH(std::size_t x)  const
```

Now I don't now what else I could do.

**Comment by stla** [comment]
I found the backtrace command:

```
(gdb) bt
#0  0x00007fffc634469d in CGAL::internal::chained_map<std::pair<int, int>, std::allocator<std::pair<int, int> > >::access (x=4636, this=0x7fffffff9e38)
    at /home/stla/R/x86_64-pc-linux-gnu-library/4.3/RcppCGAL/include/CGAL/Hash_map/internal/chained_map.h:64
#1  CGAL::Unique_hash_map<CGAL::SM_Halfedge_index, std::pair<int, int>, boost::hash<CGAL::SM_Halfedge_index>, std::allocator<std::pair<int, int> > >::operator[] (key=<synthetic pointer>..., this=0x7fffffff9e30)
    at /home/stla/R/x86_64-pc-linux-gnu-library/4.3/RcppCGAL/include/CGAL/Unique_hash_map.h:116
#2  boost::associative_property_map<CGAL::Unique_hash_map<CGAL::SM_Halfedge_index, std::pair<int, int>, boost::hash<CGAL::SM_Halfedge_index>, std::allocator<std::pair<int, int> > > >::operator[] (this=<synthetic pointer>, 
    k=<synthetic pointer>...)
    at /home/stla/R/x86_64-pc-linux-gnu-library/4.3/RcppCGAL/include/CGAL/Unique_hash_map.h:157
#3  boost::put (val=..., key=<synthetic pointer>..., 
    uhm=<synthetic pointer>...)
    at /home/stla/R/x86_64-pc-linux-gnu-library/4.3/RcppCGAL/include/CGAL/Unique_hash_map.h:171
#4  CGAL::Surface_mesh_parameterization::ARAP_parameterizer_3<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >, CGAL::Surface_mesh_parameterization::Circular_border_arc_length_parameterizer_3<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >, CGAL::Default>::compute_local_parameterization (this=<optimized out>, 
    mesh=..., faces=std::vector of length 539546, capacity 1048576 = {...}, 
    lp=std::vector of length 0, capacity 0, lpmap=...)
    at /home/stla/R/x86_64-pc-linux-gnu-library/4.3/RcppCGAL/include/CGAL/Surface_mesh_parameterization/ARAP_parameterizer_3.h:928
#5  0x00007fffc63762f3 in CGAL::Surface_mesh_parameterization::ARAP_parameterizer_3<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >, CGAL::Surface_mesh_parameterization::Circular_border_arc_length_parameterizer_3<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >, CGAL::Default>::parameterize<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >::Property_map<CGAL::SM_Vertex_index, CGAL::Point_2<CGAL::Epick> >, CGAL::internal::Dynamic<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick--Type <RET> for more, q to quit, c to continue without paging--
ndex, int> >, CGAL::internal::Dynamic<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >::Property_map<CGAL::SM_Vertex_index, bool> > > (this=this@entry=0x7fffffffa0d0, mesh=..., 
    bhd=bhd@entry=..., uvmap=..., vimap=..., vpmap=...) at /usr/include/c++/9/bits/stl_vector.h:94
#6  0x00007fffc6376cd1 in CGAL::Surface_mesh_parameterization::parameterize<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >, CGAL::Surface_mesh_parameterization::ARAP_parameterizer_3<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >, CGAL::Surface_mesh_parameterization::Circular_border_arc_length_parameterizer_3<CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> > >, CGAL::Default>, CGAL::SM_Halfedge_index, CGAL::Surface_mesh<CGAL::Point_3<CGAL::Epick> >::Property_map<CGAL::SM_Vertex_index, CGAL::Point_2<CGAL::Epick> > > (mesh=..., parameterizer=..., bhd=bhd@entry=..., uvmap=...) at /home/stla/R/x86_64-pc-linux-gnu-library/4.3/RcppCGAL/include/CGAL/Surface_mesh/Properties.h:575
#7  0x00007fffc633789f in testparam (filename="/home/stla/Documents/R/MyPackages/cgalMeshes/inst/trash/torus.off", method=method@entry=3) at /usr/include/c++/9/ext/atomicity.h:96
#8  0x00007fffc6205678 in _cgalMeshes_testparam (filenameSEXP=<optimized out>, methodSEXP=<optimized out>) at /usr/include/c++/9/ext/new_allocator.h:89
#9  0x00007ffff7c4bbba in ?? () from /usr/lib/R/lib/libR.so
#10 0x00007ffff7c8ede9 in ?? () from /usr/lib/R/lib/libR.so
#11 0x00007ffff7ca2c78 in Rf_eval () from /usr/lib/R/lib/libR.so
#12 0x00007ffff7ca503e in ?? () from /usr/lib/R/lib/libR.so
#13 0x00007ffff7ca5eb2 in Rf_applyClosure () from /usr/lib/R/lib/libR.so
#14 0x00007ffff7ca2e9f in Rf_eval () from /usr/lib/R/lib/libR.so
#15 0x00007ffff7ca81e2 in ?? () from /usr/lib/R/lib/libR.so
#16 0x00007ffff7ca317b in Rf_eval () from /usr/lib/R/lib/libR.so
#17 0x00007ffff7cd8c72 in Rf_ReplIteration () from /usr/lib/R/lib/libR.so
#18 0x00007ffff7cd9010 in ?? () from /usr/lib/R/lib/libR.so
#19 0x00007ffff7cd90d0 in run_Rmainloop () from /usr/lib/R/lib/libR.so
#20 0x000055555555509f in main ()
#21 0x00007ffff7983083 in __libc_start_main (main=0x555555555080 <main>, argc=3, argv=0x7fffffffdd18, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdd08) at ../csu/libc-start.c:308
#22 0x00005555555550de in _start ()
```

**Comment by stla** [comment]
Yes!!!! It has not crashed after I rebuilt the package. But I also modified the code. Let me try the original code of the example and probably I'll close this issue.
